let SESSIONID;
SESSIONID = '-2ba9dcce3a1dde684d18726a69e2007a';

/*
{
    "id": "d054b2ae-5851-4cae-ab3d-c91e2f94a29e",
    "username": "btp_po_l1_l2@asia.meap.com",
    "email": "btp_po_l1_l2@asia.meap.com",
    "familyName": "BTP PO L1 L2",
    "origin": "sap.custom",
    "externalId": "btp_po_l1_l2@asia.meap.com",
    "zoneId": "8b000472-9622-4622-88d1-ad2954c03ad2",
    "verified": false,
    "legacyVerificationBehavior": false,
    "roleCollections": [
        "ZSG_BTP_SD_SO.1822_LEVEL_DEF_BB",
        "ZSG_BTP_SD_SO.1822_LEVEL_2",
        "Sales_Order"
    ],
    "version": 0
}
 */
async function getRoles(userid) {
    const url = "https://emea.cockpit.btp.cloud.sap/ajax/1a9a42eb-f11a-4aab-a27a-f1d3523c7db2/cf-ap10/8b000472-9622-4622-88d1-ad2954c03ad2/getUserRoleCollectionAssignments/8b000472-9622-4622-88d1-ad2954c03ad2/sap.custom"
    const response = await fetch(`${url}?userid=${userid}`, {
        "credentials": "include",
        "headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0",
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.5",
            "Content-Type": "application/json",
            "X-ClientSession-Id": SESSIONID,
            "X-Requested-With": "XMLHttpRequest",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin"
        },
        "referrer": "https://emea.cockpit.btp.cloud.sap/cockpit",
        "method": "GET",
        "mode": "cors"
    });

    const userDetails = await response.json();
    return userDetails;
}

/*
body
{
            "id": "d054b2ae-5851-4cae-ab3d-c91e2f94a29e",
            "username": "btp_po_l1_l2@asia.meap.com",
            "email": "btp_po_l1_l2@asia.meap.com",
            "familyName": "BTP PO L1 L2",
            "origin": "sap.custom",
            "externalId": "btp_po_l1_l2@asia.meap.com",
            "zoneId": "8b000472-9622-4622-88d1-ad2954c03ad2",
            "verified": false,
            "legacyVerificationBehavior": false,
            "roleCollections": ["ZSG_BTP_SD_SO.1822_LEVEL_DEF_BB", "ZSG_BTP_SD_SO.1822_LEVEL_2", "Sales_Order", "~q22_900_Z_APP.SECURITY.ADM_ISS"],
            "version": 0
        }
 */
async function updateRoleCollectionAssignments(userId, userDetails) {
    const url = "https://emea.cockpit.btp.cloud.sap/ajax/1a9a42eb-f11a-4aab-a27a-f1d3523c7db2/cf-ap10/8b000472-9622-4622-88d1-ad2954c03ad2/updateUserRoleCollection/8b000472-9622-4622-88d1-ad2954c03ad2"
    await fetch(`${url}?userid=${userId}`, {
        "credentials": "include",
        "headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0",
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.5",
            "Content-Type": "application/json",
            "X-ClientSession-Id": SESSIONID,
            "X-Requested-With": "XMLHttpRequest",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "Priority": "u=1"
        },
        "referrer": "https://emea.cockpit.btp.cloud.sap/cockpit",
        "body": JSON.stringify(userDetails),
        "method": "PUT",
        "mode": "cors"
    });
}

async function main() {
    // const oUserDetails = await getRoles(ORIGINAL_USER);
    // const oClonedDetails = await getRoles(CLONED_USER);

    for (let email of ASSINGMMENT) {
        const oUserDetails = await getRoles(email);
        if (oUserDetails) {
            oUserDetails.roleCollections.push("Process_Approver");
            oUserDetails.roleCollections.push("ProcessAutomationAdmin");
            oUserDetails.roleCollections.push("ProcessAutomationParticipant");
            await updateRoleCollectionAssignments(email, oUserDetails);
        }
    }


}


ASSINGMMENT = [
    "Abel.Neui@asia.meap.com",
    "Aiying.Tan@asia.meap.com",
    "alex.liew@asia.meap.com",
    "ATSG-CS10@alps-logistics.com",
    "Andrew.Shen@asia.meap.com",
    "andrew.yeong@asia.meap.com",
    "Angel.Ooi@asia.meap.com",
    "ANGELOOI_C@asia.meap.com",
    "Anrine.Kee@asia.meap.com",
    "Anthony.Fung@asia.meap.com",
    "benedict.bugarin@asia.meap.com",
    "BiJun.Tan@asia.meap.com",
    "BoonTeck.Chua@asia.meap.com",
    "BoonTeck.Teo@asia.meap.com",
    "bosen.huang@asia.meap.com",
    "BOSENHUANG_C@asia.meap.com",
    "bpensie_c@asia.meap.com",
    "btp_po_l1@asia.meap.com",
    "btp_po_l1_l2@asia.meap.com",
    "btp_po_l1_l2_l3@asia.meap.com",
    "btp_po_l1_l3@asia.meap.com",
    "btp_po_l2@asia.meap.com",
    "btp_po_l2_l3@asia.meap.com",
    "btp_po_l3@asia.meap.com",
    "Cecilia.Ng@asia.meap.com",
    "cfteoh_c@asia.meap.com",
    "CheeYen.Tan@asia.meap.com",
    "chengfook.teoh@asia.meap.com",
    "chintong.chong@asia.meap.com",
    "ChoonChin.Tay@asia.meap.com",
    "ChoonHiok.Tay@asia.meap.com",
    "ChoyTing.Chew@asia.meap.com",
    "Christabel.Lee@asia.meap.com",
    "chtay_c@asia.meap.com",
    "ChuanWan.Chiam@asia.meap.com",
    "ChungMong.Voo@asia.meap.com",
    "Clara.Lim@asia.meap.com",
    "Clara.Tan@asia.meap.com",
    "Clifford.Chua@asia.meap.com",
    "co-om_ioadm@asia.meap.com",
    "Cyndi.Lim@asia.meap.com",
    "Damien.Yuen@asia.meap.com",
    "Daniel.Lee@asia.meap.com",
    "Dave.Heng@asia.meap.com",
    "debtanu.basak@asia.meap.com",
    "Denise.Hong@asia.meap.com",
    "Denis.Tan@asia.meap.com",
    "Deon.Liew@asia.meap.com",
    "deonliew_c@asia.meap.com",
    "Derek.Lee@asia.meap.com",
    "Dianna.Cher@asia.meap.com",
    "DR-SD01@asia.meap.com",
    "ea_nichung@asia.meap.com",
    "edwin.li@asia.meap.com",
    "elaine.keh@asia.meap.com",
    "Elaine.Ong@asia.meap.com",
    "elaine.yang@asia.meap.com",
    "Elvin.Koh@asia.meap.com",
    "elvin_koh_yt@asia.meap.com",
    "Emma.Li@asia.meap.com",
    "emme.eng@asia.meap.com",
    "engeng.goh@asia.meap.com",
    "Evelyn.Tan@asia.meap.com",
    "Evelyn.Woon@asia.meap.com",
    "FangWee.Lim@asia.meap.com",
    "fi-aa_pro@asia.meap.com",
    "fi-ap_logi@asia.meap.com",
    "fi-ap_pro@asia.meap.com",
    "fi-ap_venadm@asia.meap.com",
    "FI-AR_PRO@asia.meap.com",
    "fi-ar_pymt@asia.meap.com",
    "fi-gl_adm@asia.meap.com",
    "fi-gl_dsp@asia.meap.com",
    "fi-gl_pro@asia.meap.com",
    "FongTing.Lim@asia.meap.com",
    "francisca.kwan@asia.meap.com",
    "frederick.goh@asia.meap.com",
    "Garry.Quek@asia.meap.com",
    "GekEng.Tang@asia.meap.com",
    "grace.chan@asia.meap.com",
    "gracechan_c@asia.meap.com",
    "Grace.Chua@asia.meap.com",
    "heidi.tan@asia.meap.com",
    "hokim.ng@asia.meap.com",
    "HueyShyan.Yoon@asia.meap.com",
    "HuiLing.Ong@asia.meap.com",
    "Irina.Yeo@asia.meap.com",
    "Irving.Wong@asia.meap.com",
    "Ivy.Lim@asia.meap.com",
    "jason.liew@asia.meap.com",
    "Jason.Ong@asia.meap.com",
    "jaysonroy.almare@asia.meap.com",
    "Jeffrey.Chia@asia.meap.com",
    "Jessie.Tan@asia.meap.com",
    "JiannHorng.Lui@asia.meap.com",
    "jiaqi.ong@asia.meap.com",
    "JingEn.Chong@asia.meap.com",
    "JinqShyan.Ng@asia.meap.com",
    "John.Chong@asia.meap.com",
    "John.Teo@asia.meap.com",
    "john_teo_yt@asia.meap.com",
    "Joyce.Lee@asia.meap.com",
    "joyce.sumitha@asia.meap.com",
    "KaiSia.Lee@asia.meap.com",
    "kalpesh.ashar@asia.meap.com",
    "Karen.See@asia.meap.com",
    "KAREN.SEE_C@asia.meap.com",
    "Katherine.Tan@asia.meap.com",
    "Kathrine.Lee@asia.meap.com",
    "kelvin.loh@asia.meap.com",
    "kenneth.chang@asia.meap.com",
    "Kenneth.Tong@asia.meap.com",
    "KhengTiong.Low@asia.meap.com",
    "kienli.yew@asia.meap.com",
    "kris.teo@asia.meap.com",
    "LengLeng.Soh@asia.meap.com",
    "Leonggee.Aw@asia.meap.com",
    "Levinon.Nobrera@asia.meap.com",
    "LiKhuan.Tay@asia.meap.com",
    "LiLin.Kong@asia.meap.com",
    "LKTAY_C@asia.meap.com",
    "lmeng_c@asia.meap.com",
    "maikee.gan@asia.meap.com",
    "mamidi.duryodhana@asia.meap.com",
    "Manohar.Bathina@asia.meap.com",
    "Marcus.Yong@asia.meap.com",
    "Masanori.Yamada@asia.meap.com",
    "Matthew.Seet@asia.meap.com",
    "mc-psuser01@asia.meap.com",
    "MeiQi.Tan@asia.meap.com",
    "MeiSum.Woo@asia.meap.com",
    "mkgan_c@asia.meap.com",
    "mlchua_c@asia.meap.com",
    "mm-833@asia.meap.com",
    "mm-835@asia.meap.com",
    "MongPing.Ng@asia.meap.com",
    "mpng_c@asia.meap.com",
    "Muisun.Chai@asia.meap.com",
    "MunLeng.Chua@asia.meap.com",
    "myintthuzar.khin@asia.meap.com",
    "nicholas.chong@asia.meap.com",
    "Nicholas.Hung@asia.meap.com",
    "Nigel.Ho@asia.meap.com",
    "Noriaki.Onishi@asia.meap.com",
    "patrick.chu@asia.meap.com",
    "Pauline.Thng@asia.meap.com",
    "PengLeong.Ho@asia.meap.com",
    "Pensie.B@asia.meap.com",
    "portaltechuser@sap.com",
    "Priscilla.Ong@asia.meap.com",
    "Randy.Xu@asia.meap.com",
    "raymod_wc@asia.meap.com",
    "raymond.tan@asia.meap.com",
    "Royston.Kwik@asia.meap.com",
    "Sachin.As@asia.meap.com",
    "Samantha.Tan@asia.meap.com",
    "Sani.Saleh@asia.meap.com",
    "saumya.mazoom@asia.meap.com",
    "sd-812@asia.meap.com",
    "selvi.mathivanan@asia.meap.com",
    "seonghong.lim@asia.meap.com",
    "ShiaYin.Lim@asia.meap.com",
    "shiming.chua@asia.meap.com",
    "SiangLiang.Sim@asia.meap.com",
    "SiewFeng.Tan@asia.meap.com",
    "SiewHuay.Ong@asia.meap.com",
    "SiewLian.Quek@asia.meap.com",
    "SiewPeng.Low@asia.meap.com",
    "SIMSL_C@asia.meap.com",
    "SinYee.Tham@asia.meap.com",
    "sivananthni.v@asia.meap.com",
    "Sofya.Nurul@asia.meap.com",
    "SoonLeng.Tan@asia.meap.com",
    "sourav.das@asia.meap.com",
    "sourav.das@asia.meap.com",
    "sourav.masid@asia.meap.com",
    "srini.karu@asia.meap.com",
    "srini.karu@asia.meap.com",
    "Steven.Teo@asia.meap.com",
    "steven_wc@asia.meap.com",
    "suresh.lakshmi@asia.meap.com",
    "TaiWei.Ng@asia.meap.com",
    "Takahito.Noda@asia.meap.com",
    "terence.liew@asia.meap.com",
    "TEST-KAREN@asia.meap.com",
    "testodata@asia.meap.com",
    "Tom.Yong@asia.meap.com",
    "tom_yong_yt@asia.meap.com",
    "trg_btp_01@asia.meap.com",
    "trg_btp_02@asia.meap.com",
    "TRG_BTP_03@asia.meap.com",
    "TRG_BTP_04@asia.meap.com",
    "trg_fi_aa_01@asia.meap.com",
    "trg_lo_fa_01@asia.meap.com",
    "trg_log_01@asia.meap.com",
    "trg_uat_fi_01@asia.meap.com",
    "trg_uat_fi@asia.meap.com",
    "trg_uat_log_01@asia.meap.com",
    "TRG_UAT_LOGI@asia.meap.com",
    "Tsutomu.Sekizawa@asia.meap.com",
    "Uday.Nyamgoud@asia.meap.com",
    "Victoria.Choo@asia.meap.com",
    "virgilio.sanchez@asia.meap.com",
    "WaiMun.Leong@asia.meap.com",
    "WaiYin.Lee@asia.meap.com",
    "WeePheng.Lau@asia.meap.com",
    "WeiSze.Lee@asia.meap.com",
    "WenMan.Wang@asia.meap.com",
    "whchui_sv@asia.meap.com",
    "Whelan.Lee@asia.meap.com",
    "Wilfred.Cher@asia.meap.com",
    "Winghong.Chui@asia.meap.com",
    "Winston.Chin@asia.meap.com",
    "winston_yt@asia.meap.com",
    "XinYi.Oh@asia.meap.com",
    "Yasuo.Watanabe@asia.meap.com",
    "YiShan.Tan@asia.meap.com",
    "YiYuan.Ng@asia.meap.com",
    "YSTAN_C@asia.meap.com",
    "Yuka.Iwasaki@asia.meap.com",
    "Yunita.Halim@asia.meap.com",
    "Yvonne.Chia@asia.meap.com",
    "yvonnechia_c@asia.meap.com",
    "zoe.quek@asia.meap.com",
    "Zona.Liew@asia.meap.com"
]

main()
